### PR TITLE
Add all dev tools explicitly in YAML specs (was "Finalize initial RStudio base-image")

### PR DESCRIPTION
**Pull request by davclark**
THIS SHOULD BE MERGED WHEN CURRENT INTEGRATION IS MERGED INTO DEPLOYMENT.

Note that this is actually a version of the rserver branch with the rstudio-server image removed. This is to avoid inadvertently publishing RStudio on the cloud for now.

Even so, this PR implements the changes to dev tools required by the rserver logic now in integration. So, it's the last step in closing what was issue 16 (which was transformed into this PR via GitHub's `hub prq` tool - learn something new every day).

Most changes involve copying the previous version of a base, and simply adding `- notebook` to the development tool list. There are also very small changes to the python2-minimal base to re-add conda-forge, so you'll see those changes in the Dockerfile.

### CODE REVIEW

**Comment by davclark** [comment]
Further discussion with @dkleissa on Slack led to the belief that we should actually be fine to distribute the actually Libre version of RStudio, as long as we respect the AGPL license. We do this twice over - we don't modify the codebase, and we publish the code we use to bundle / configure it.

**Comment by dkleissa** [comment]
closing as these changes have been added to #19.

**Comment by davclark** [comment]
The essential change, which is modifying the way dev tools are listed, was not copied over.

**Comment by davclark** [comment]
Actually, this was missing only from python2-minimal in cudanew. It's now fixed.

**Pull request closed without merging**
